# Generated by Django 2.2.2 on 2019-07-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('code_postal', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_de_surface', models.CharField(max_length=200)),
                ('surface_approximative', models.CharField(max_length=200)),
                ('chauffage', models.CharField(max_length=200)),
            ],
        ),
    ]
