# Generated by Django 2.2.2 on 2019-07-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sold',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='chauffage',
            field=models.CharField(choices=[('electricité', 'electricité'), ('fioul', 'Fioul'), ('gaz', 'Gaz'), ('pompe à chaleur', 'Pompe à chaleur'), ('autre', 'Autre')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='surface_approximative',
            field=models.CharField(choices=[('0-50', '0 à 50m2'), ('50-100', '50 à 100m2'), ('100-150', '100 à 150m2'), ('150-200', '150 à 200m2'), ('200+', '200m2 et plus')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='type_de_surface',
            field=models.CharField(choices=[('garage', 'garage annexe'), ('caves et sous-sol', 'cave et sous-sol'), ('combles', 'combles'), ('vide sanitaires', 'vide sanitaire')], default=None, max_length=200),
        ),
    ]
