# Generated by Django 2.2.2 on 2019-08-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190730_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='surface_approximative',
            field=models.CharField(choices=[('0 à 50m2', '0 à 50m2'), ('50 à 100m2', '50 à 100m2'), ('100 à 150m2', '100 à 150m2'), ('150 à 200m2', '150 à 200m2'), ('200m2 et plus', '200m2 et plus')], default=None, max_length=200),
        ),
    ]
