# Generated by Django 2.2.2 on 2019-08-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190802_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='chauffage',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='surface_approximative',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='type_de_surface',
        ),
    ]
